services:
  app:
    container_name: skillnotes-app
    image: docker.io/node:24.5.0-bookworm
    volumes:
      - ./:/app
    env_file:
      - ./.env
    # command: sh -c 'cd /app && npm run migrate && npm run dev'
    command: sh -c 'cd /app && npm run migrate && npm start'
    networks:
      skillnotes_network:
        aliases:
          - app
    restart: unless-stopped
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: ${APP_CPUS}
          memory: ${APP_MEMORY}
    depends_on:
      - db
  db:
    container_name: skillnotes-db
    image: docker.io/postgres:15.14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      skillnotes_network:
        aliases:
          - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${DB_CPUS}
          memory: ${DB_MEMORY}
networks:
  skillnotes_network:
    driver: bridge
